In [1]:
import pandas as pd

df = pd.read_csv(r"D:\Projects\Data\Supply_Chain_dataset.csv")

In [2]:
df.head()

,Type,Days_for_shipping_(real),Days_for_shipment_(scheduled),Benefit_per_order,Sales_per_customer,Delivery_Status,Late_delivery_risk,Category_Id,Category_Name,Customer_City,...,Order_Zipcode,Product_Card_Id,Product_Category_Id,Product_Description,Product_Image,Product_Name,Product_Price,Product_Status,shipping_date_(DateOrders),Shipping_Mode
0,DEBIT,3,4,91.25000,314.64001,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018,Standard Class
1,TRANSFER,5,4,-249.09000,311.35999,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018,Standard Class
2,CASH,4,4,-247.78000,309.72000,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018,Standard Class
3,DEBIT,3,4,22.86000,304.81000,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018,Standard Class
4,PAYMENT,2,4,134.21001,298.25000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018,Standard Class

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days_for_shipping_(real)       180519 non-null  int64
 2   Days_for_shipment_(scheduled)  180519 non-null  int64
 3   Benefit_per_order              180519 non-null  float64
 4   Sales_per_customer             180519 non-null  float64
 5   Delivery_Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category_Id                    180519 non-null  int64
 8   Category_Name                  180519 non-null  str
 9   Customer_City                  180519 non-null  str
 10  Customer_Country               180519 non-null  str
 11  Customer_Email                 180519 non-null  str
 12  Customer_Fname                 180519 non-null  str
 13  Customer_Id                    180519 non-null  int64
 14  Customer_Lname                 180511 non-null  str
 15  Customer_Password              180519 non-null  str
 16  Customer_Segment               180519 non-null  str
 17  Customer_State                 180519 non-null  str
 18  Customer_Street                180519 non-null  str
 19  Customer_Zipcode               180516 non-null  float64
 20  Department_Id                  180519 non-null  int64
 21  Department_Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order_City                     180519 non-null  str
 26  Order_Country                  180519 non-null  str
 27  Order_Customer_Id              180519 non-null  int64
 28  order_date_(DateOrders)        180519 non-null  str
 29  Order_Id                       180519 non-null  int64
 30  Order_Item_Cardprod_Id         180519 non-null  int64
 31  Order_Item_Discount            180519 non-null  float64
 32  Order_Item_Discount_Rate       180519 non-null  float64
 33  Order_Item_Id                  180519 non-null  int64
 34  Order_Item_Product_Price       180519 non-null  int64
 35  Order_Item_Profit_Ratio        180519 non-null  float64
 36  Order_Item_Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order_Item_Total               180519 non-null  float64
 39  Order_Profit_Per_Order         180519 non-null  float64
 40  Order_Region                   180519 non-null  str
 41  Order_State                    180519 non-null  str
 42  Order_Status                   180519 non-null  str
 43  Order_Zipcode                  24843 non-null   float64
 44  Product_Card_Id                180519 non-null  int64
 45  Product_Category_Id            180519 non-null  int64
 46  Product_Description            0 non-null       float64
 47  Product_Image                  180519 non-null  str
 48  Product_Name                   180519 non-null  str
 49  Product_Price                  180519 non-null  float64
 50  Product_Status                 180519 non-null  int64
 51  shipping_date_(DateOrders)     180519 non-null  str
 52  Shipping_Mode                  180519 non-null  str
dtypes: float64(14), int64(15), str(24)
memory usage: 73.0 MB

- Removed the `Order_Zipcode` and `Product_Description` columns, as they are not relevant to the project's KPIs and contain more than 75% missing values.

In [4]:
df = df.drop(columns="Order_Zipcode")
df = df.drop(columns="Product_Description")

In [5]:
df.isnull().sum()

Type                             0
Days_for_shipping_(real)         0
Days_for_shipment_(scheduled)    0
Benefit_per_order                0
Sales_per_customer               0
Delivery_Status                  0
Late_delivery_risk               0
Category_Id                      0
Category_Name                    0
Customer_City                    0
Customer_Country                 0
Customer_Email                   0
Customer_Fname                   0
Customer_Id                      0
Customer_Lname                   8
Customer_Password                0
Customer_Segment                 0
Customer_State                   0
Customer_Street                  0
Customer_Zipcode                 3
Department_Id                    0
Department_Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order_City                       0
Order_Country                    0
Order_Customer_Id                0
order_date_(DateOrders)          0
Order_Id                         0
Order_Item_Cardprod_Id           0
Order_Item_Discount              0
Order_Item_Discount_Rate         0
Order_Item_Id                    0
Order_Item_Product_Price         0
Order_Item_Profit_Ratio          0
Order_Item_Quantity              0
Sales                            0
Order_Item_Total                 0
Order_Profit_Per_Order           0
Order_Region                     0
Order_State                      0
Order_Status                     0
Product_Card_Id                  0
Product_Category_Id              0
Product_Image                    0
Product_Name                     0
Product_Price                    0
Product_Status                   0
shipping_date_(DateOrders)       0
Shipping_Mode                    0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['shipping_date_(DateOrders)'] = pd.to_datetime(df['shipping_date_(DateOrders)']) # turn the shipping date column into datetime format

In [9]:
df[['shipping_date_(DateOrders)', 'Order_Status', 'Product_Status']].head(10)

  shipping_date_(DateOrders)     Order_Status  Product_Status
0                 2018-02-03         COMPLETE               0
1                 2018-01-18          PENDING               0
2                 2018-01-17           CLOSED               0
3                 2018-01-16         COMPLETE               0
4                 2018-01-15  PENDING_PAYMENT               0
5                 2018-01-19         CANCELED               0
6                 2018-01-15         COMPLETE               0
7                 2018-01-15       PROCESSING               0
8                 2018-01-16           CLOSED               0
9                 2018-01-15           CLOSED               0

In [15]:
df['Product_Status'].unique()

array([0])

In [11]:
df.dropna(subset=['Product_Status'], inplace=True)

In [12]:
df['Order_Country'].unique()

<StringArray>
[          'Indonesia',               'India',           'Australia',
               'China',               'Japon',       'Corea del Sur',
            'Singapur',             'Turquia',            'Mongolia',
      'Estados Unidos',
 ...
           'Eslovenia', 'Republica de Gambia',            'Botsuana',
             'Armenia',   'Guinea Ecuatorial',              'Kuwait',
               'Butan',                'Chad',              'Serbia',
   'Sahara Occidental']
Length: 164, dtype: str