In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"D:\Projects\Data\Supply_Chain_dataset.csv")

df['shipping_date_(DateOrders)'] = pd.to_datetime(df['shipping_date_(DateOrders)'])
df = df.drop(columns="Order_Zipcode")
df = df.drop(columns="Product_Description")
df = df.drop(columns="Product_Image")
df = df.drop(columns="Customer_Email")
df = df.drop(columns="Product_Status")
df = df.drop(columns="Customer_Password")
df = df.dropna()
df.drop('Order_Profit_Per_Order', axis=1, inplace=True)

duplicate_cols = []
for i in range(len(df.columns)):
    for j in range(i + 1, len(df.columns)):
        if df.iloc[:, i].equals(df.iloc[:, j]):
            duplicate_cols.append(df.columns[j])

df = df.drop(columns=duplicate_cols)

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 180508 entries, 0 to 180518
Data columns (total 42 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180508 non-null  str
 1   Days_for_shipping_(real)       180508 non-null  int64
 2   Days_for_shipment_(scheduled)  180508 non-null  int64
 3   Benefit_per_order              180508 non-null  float64
 4   Sales_per_customer             180508 non-null  float64
 5   Delivery_Status                180508 non-null  str
 6   Late_delivery_risk             180508 non-null  int64
 7   Category_Id                    180508 non-null  int64
 8   Category_Name                  180508 non-null  str
 9   Customer_City                  180508 non-null  str
 10  Customer_Country               180508 non-null  str
 11  Customer_Fname                 180508 non-null  str
 12  Customer_Id                    180508 non-null  int64
 13  Customer_Lname                 180508 non-null  str
 14  Customer_Segment               180508 non-null  str
 15  Customer_State                 180508 non-null  str
 16  Customer_Street                180508 non-null  str
 17  Customer_Zipcode               180508 non-null  float64
 18  Department_Id                  180508 non-null  int64
 19  Department_Name                180508 non-null  str
 20  Latitude                       180508 non-null  float64
 21  Longitude                      180508 non-null  float64
 22  Market                         180508 non-null  str
 23  Order_City                     180508 non-null  str
 24  Order_Country                  180508 non-null  str
 25  order_date_(DateOrders)        180508 non-null  str
 26  Order_Id                       180508 non-null  int64
 27  Order_Item_Cardprod_Id         180508 non-null  int64
 28  Order_Item_Discount            180508 non-null  float64
 29  Order_Item_Discount_Rate       180508 non-null  float64
 30  Order_Item_Id                  180508 non-null  int64
 31  Order_Item_Product_Price       180508 non-null  int64
 32  Order_Item_Profit_Ratio        180508 non-null  float64
 33  Order_Item_Quantity            180508 non-null  int64
 34  Sales                          180508 non-null  float64
 35  Order_Region                   180508 non-null  str
 36  Order_State                    180508 non-null  str
 37  Order_Status                   180508 non-null  str
 38  Product_Name                   180508 non-null  str
 39  Product_Price                  180508 non-null  float64
 40  shipping_date_(DateOrders)     180508 non-null  datetime64[us]
 41  Shipping_Mode                  180508 non-null  str
dtypes: datetime64[us](1), float64(10), int64(11), str(20)
memory usage: 59.2 MB

In [29]:
df.iloc[:, 0:15].head(10)

,Type,Days_for_shipping_(real),Days_for_shipment_(scheduled),Benefit_per_order,Sales_per_customer,Delivery_Status,Late_delivery_risk,Category_Id,Category_Name,Customer_City,Customer_Country,Customer_Fname,Customer_Id,Customer_Lname,Customer_Segment
0,DEBIT,3,4,91.25000,314.64001,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer
1,TRANSFER,5,4,-249.09000,311.35999,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer
2,CASH,4,4,-247.78000,309.72000,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer
3,DEBIT,3,4,22.86000,304.81000,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office
4,PAYMENT,2,4,134.21001,298.25000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate
5,TRANSFER,6,4,18.58000,294.98001,Shipping canceled,0,73,Sporting Goods,Tonawanda,EE. UU.,Kimberly,19488,Flowers,Consumer
6,DEBIT,2,1,95.18000,288.42001,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Constance,19487,Terrell,Home Office
7,TRANSFER,2,1,68.43000,285.14001,Late delivery,1,73,Sporting Goods,Miami,EE. UU.,Erica,19486,Stevens,Corporate
8,CASH,3,2,133.72000,278.59000,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Nichole,19485,Olsen,Corporate
9,CASH,2,1,132.14999,275.31000,Late delivery,1,73,Sporting Goods,San Ramon,EE. UU.,Oprah,19484,Delacruz,Corporate

In [30]:
df.iloc[:, 16:30].head(10)

,Customer_Street,Customer_Zipcode,Department_Id,Department_Name,Latitude,Longitude,Market,Order_City,Order_Country,order_date_(DateOrders),Order_Id,Order_Item_Cardprod_Id,Order_Item_Discount,Order_Item_Discount_Rate
0,5365 Noble Nectar Island,725.0,2,Fitness,18.25145,-66.03706,Pacific Asia,Bekasi,Indonesia,1/31/2018,77202,1360,13.11,0.04
1,2679 Rustic Loop,725.0,2,Fitness,18.27945,-66.03706,Pacific Asia,Bikaner,India,1/13/2018,75939,1360,16.39,0.05
2,8510 Round Bear Gate,95125.0,2,Fitness,37.29223,-121.88128,Pacific Asia,Bikaner,India,1/13/2018,75938,1360,18.03,0.06
3,3200 Amber Bend,90027.0,2,Fitness,34.12595,-118.29102,Pacific Asia,Townsville,Australia,1/13/2018,75937,1360,22.94,0.07
4,8671 Iron Anchor Corners,725.0,2,Fitness,18.25377,-66.03705,Pacific Asia,Townsville,Australia,1/13/2018,75936,1360,29.50,0.09
5,2122 Hazy Corner,14150.0,2,Fitness,43.01397,-78.87907,Pacific Asia,Toowoomba,Australia,1/13/2018,75935,1360,32.78,0.10
6,1879 Green Pine Bank,725.0,2,Fitness,18.24254,-66.03706,Pacific Asia,Guangzhou,China,1/13/2018,75934,1360,39.33,0.12
7,7595 Cotton Log Row,33162.0,2,Fitness,25.92887,-80.16287,Pacific Asia,Guangzhou,China,1/13/2018,75933,1360,42.61,0.13
8,2051 Dusty Route,725.0,2,Fitness,18.23322,-66.03706,Pacific Asia,Guangzhou,China,1/13/2018,75932,1360,49.16,0.15
9,9139 Blue Blossom Court,94583.0,2,Fitness,37.77399,-121.96663,Pacific Asia,Guangzhou,China,1/13/2018,75931,1360,52.44,0.16

In [31]:
df.iloc[:, 31:43].head(10)

,Order_Item_Product_Price,Order_Item_Profit_Ratio,Order_Item_Quantity,Sales,Order_Region,Order_State,Order_Status,Product_Name,Product_Price,shipping_date_(DateOrders),Shipping_Mode
0,328,0.29,1,327.75,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,2018-02-03,Standard Class
1,328,-0.80,1,327.75,South Asia,Rajastan,PENDING,Smart watch,327.75,2018-01-18,Standard Class
2,328,-0.80,1,327.75,South Asia,Rajastan,CLOSED,Smart watch,327.75,2018-01-17,Standard Class
3,328,0.08,1,327.75,Oceania,Queensland,COMPLETE,Smart watch,327.75,2018-01-16,Standard Class
4,328,0.45,1,327.75,Oceania,Queensland,PENDING_PAYMENT,Smart watch,327.75,2018-01-15,Standard Class
5,328,0.06,1,327.75,Oceania,Queensland,CANCELED,Smart watch,327.75,2018-01-19,Standard Class
6,328,0.33,1,327.75,Eastern Asia,Guangdong,COMPLETE,Smart watch,327.75,2018-01-15,First Class
7,328,0.24,1,327.75,Eastern Asia,Guangdong,PROCESSING,Smart watch,327.75,2018-01-15,First Class
8,328,0.48,1,327.75,Eastern Asia,Guangdong,CLOSED,Smart watch,327.75,2018-01-16,Second Class
9,328,0.48,1,327.75,Eastern Asia,Guangdong,CLOSED,Smart watch,327.75,2018-01-15,First Class